### PR TITLE
Regex improvement [ISSUE 2]

### PR DESCRIPTION
**Pull request by ThatsNinja**
Used your solver today and loved it. This is the best one of these I've seen yet, and I'm happy to help however I can.

### CODE REVIEW

**Comment by cxcorp** [comment]
Thanks for the interest in the project! The new regex matches two hex digits or white space and newlines which would definitely be good for checking that the input's well-formed. The problem with the original regex was that it's missing a `*` from the end, which means it currently only matches the first character. The original regex was also relatively forgiving (not checking for two digits) because the regex is used to allow input into the field itself instead of e.g. enabling the submit button. A stricter regex that requires two digits immediately would mean that you'd have to write down the matrix beforehand and copypaste it in, right?

Would you want to change the PR to add in a `*` after the original regex's character set (the square brackets)?

**Comment by ThatsNinja** [comment]
I'm iterating on this now and was just realizing that full validation will be sort of ambitious. I will add more commits shortly.

Again, happy to help!

**Comment by cxcorp** [comment]
That's cool! How does `/[0-9a-f\s\n\r]*/i` work? Extra spaces and newlines are fine - they get trimmed away.

**Comment by ThatsNinja** [comment]
So, that regex would return a single match group as long as all the characters entered were `0-9a-f`, space, or newline, and fail to match on any single character that isn't one of those. In the event that there was one invalid character in the middle it would return two match groups, etc.

Only problem is that it would include `0-9a-f` character groups longer than two 'bytes', so this would be valid as a single match group:
`bd e9 1c 55 ff
55 7a 099999999`

**Comment by cxcorp** [comment]
> In the event that there was one invalid character in the middle it would return two match groups, etc.

Hmm, I see your point. `/^[0-9a-f\s\n\r]+$/gi`? would probably work around that - if we just allow empty strings separately (so that the user can erase the textbox).

>Only problem is that it would include 0-9a-f character groups longer than two 'bytes',

Good point! A longer digit like that is definitely not ideal when submitting the form. I think we should allow it when just editing the text box though. For example, if you make a typo and want to erase a digit but misplace your cursor on a space between two bytes and hit backspace, nothing will happen since the regex forbids it, which would feel a bit "restrictive" to me. So I think it's better to be be more forgiving in the text box editor, and display a validation error in some other form that doesn't take away control from the user.

**Comment by ThatsNinja** [comment]
So, I was headed in a direction where the value of the matrix box could be automatically delimited as the hexes were verified. Like if a user isn't entering spaces that they would be entered in the state so that they're optional.

You may be right, though, in thinking along those lines. I wouldn't want to drag on UX by trying to be too clever about things.

**Comment by cxcorp** [comment]
Ah, I see! Since there's only a few distinct bytes actually used in the minigame and they all have a distinct first character, the entry box could also just automatically append the second digit and a space according to the first character, and when erasing a digit, erase the entire byte and its leading space. Or just go full blast custom input and listen to key events in a transparent textbox.

My biggest worry with getting _too_ clever with the text box is compatibility with virtual keyboards on mobile devices. I've tried many JS code editors online for example and a big bunch of them just don't work on mobile.

**Comment by cxcorp** [comment]
I'm also rolling out automatic code matrix & sequence detection from a full-window screenshot soon (alt+prntscr or F12 with the Steam overlay) which should be handy for PC players.

For console users, I've also got a [prototype](https://github.com/cxcorp/cyberpunk2077-hacker-camera-proto) that reads the code matrix using a mobile device's camera - still need to implement sequence box reading to that one before I roll that one out.

**Comment by ThatsNinja** [comment]
Okay, I fixed the regex, and I can help with other features wherever it makes sense. Thanks for coming along with me on this one as I learned my way around the code base!

**Comment by cxcorp** [comment]
Great! I added a LICENSE file and licensed the project under the Apache 2.0 license. Let me know if that's fine by you and I'll merge the PR.

**Comment by ThatsNinja** [comment]
Sounds great. Thank you!

**Pull request merged**
